defaults: &defaults
  # aws s3
  aws_access_key_id:           'AWS_KEY'
  aws_secret_access_key:       'AWS_ACCESS_KEY'
  aws_region:                  'us-west-2'
  aws_bucket:                  'YOUR_BUCKET'

development:
  <<: *defaults

test:
  <<: *defaults